// <auto-generated />
using System;
using KLCN060.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KLCN060.Infrastructure.Migrations
{
    [DbContext(typeof(KLCN060DbContext))]
    [Migration("20260913132621_AddCauHoiThuongGap")]
    partial class AddCauHoiThuongGap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KLCN060.Domain.CauHoiThuongGap", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"));

                    b.Property<string>("CauTraLoi")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TuKhoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaCauHoi");

                    b.ToTable("CauHoiThuongGaps");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietHoaDon"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKhoanMuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("MaHD");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietKhuyenMai", b =>
                {
                    b.Property<string>("MaPhieuDat")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaKM")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("TongKhuyenMai")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuDat", "MaKM");

                    b.HasIndex("MaKM");

                    b.ToTable("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietPhieuDat", b =>
                {
                    b.Property<string>("MaPhieuDat")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DonGiaApDung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuDat", "MaPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietPhieuDats");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietPhieuNhan", b =>
                {
                    b.Property<string>("MaPhieuNhan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("NgayNhan")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayTra")
                        .HasColumnType("date");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int");

                    b.Property<decimal>("TienPhuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuNhan", "MaPhong");

                    b.HasIndex("MaPhong");

                    b.ToTable("ChiTietPhieuNhans");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietSuDungDV", b =>
                {
                    b.Property<int>("MaChiTietDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDV"));

                    b.Property<string>("MaDV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhieuNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietDV");

                    b.HasIndex("MaDV");

                    b.HasIndex("MaPhieuNhan");

                    b.ToTable("ChiTietSuDungDVs");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaTaiKhoanThuNgan")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHD");

                    b.HasIndex("MaTaiKhoanThuNgan");

                    b.ToTable("ChiTietThanhToans");
                });

            modelBuilder.Entity("KLCN060.Domain.CoSoVatChat", b =>
                {
                    b.Property<string>("MaSo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaSo");

                    b.HasIndex("MaPhong");

                    b.ToTable("CoSoVatChats");
                });

            modelBuilder.Entity("KLCN060.Domain.DichVu", b =>
                {
                    b.Property<string>("MaDV")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiaDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVus");
                });

            modelBuilder.Entity("KLCN060.Domain.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhieuNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PhuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TienDV")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienDaCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CHUA_THANH_TOAN");

                    b.HasKey("MaHD");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPhieuNhan");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("KLCN060.Domain.Khach", b =>
                {
                    b.Property<string>("MaKhach")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaKhach");

                    b.ToTable("Khachs");
                });

            modelBuilder.Entity("KLCN060.Domain.KhuyenMai", b =>
                {
                    b.Property<string>("MaKM")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("DieuKien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiKM")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal?>("PhanTramKM")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SoLuongDaSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoLuongGioiHan")
                        .HasColumnType("int");

                    b.Property<string>("TenKM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKM");

                    b.ToTable("KhuyenMais");
                });

            modelBuilder.Entity("KLCN060.Domain.LichSuSaoLuu", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("DuongDanFile")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiThaoTac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ThoiGianThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaLichSu");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("LichSuSaoLuus");
                });

            modelBuilder.Entity("KLCN060.Domain.LoaiPhong", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PhuThu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("SoNguoiTieuChuan")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiPhongs");
                });

            modelBuilder.Entity("KLCN060.Domain.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaVaiTro");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("KLCN060.Domain.NhatKyBanGiaoCa", b =>
                {
                    b.Property<int>("MaBanGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBanGiao"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaTaiKhoanGiao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaTaiKhoanNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SoLuongPhieuTrongCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ThoiGianBanGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("TongTienMatCuoiCa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTienMatDauCa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaBanGiao");

                    b.HasIndex("MaTaiKhoanGiao");

                    b.HasIndex("MaTaiKhoanNhan");

                    b.ToTable("NhatKyBanGiaoCas");
                });

            modelBuilder.Entity("KLCN060.Domain.NhatKyThaoTac", b =>
                {
                    b.Property<long>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MaNhatKy"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DoiTuongTacDong")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MaNhatKy");

                    b.HasIndex("MaTaiKhoan");

                    b.ToTable("NhatKyThaoTacs");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuDatPhong", b =>
                {
                    b.Property<string>("MaPhieuDat")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("LoaiDatPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKhach")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("NgayDonDuKien")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayTraDuKien")
                        .HasColumnType("date");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuDat");

                    b.HasIndex("MaKhach");

                    b.ToTable("PhieuDatPhongs");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuDoiPhong", b =>
                {
                    b.Property<string>("MaPhieuDoi")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("ChenhLechGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaPhieuNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaPhongCu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaPhongMoi")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("NgayDoi")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuDoi");

                    b.HasIndex("MaPhongMoi");

                    b.HasIndex("MaPhieuNhan", "MaPhongCu");

                    b.ToTable("PhieuDoiPhongs");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuNhanPhong", b =>
                {
                    b.Property<string>("MaPhieuNhan")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MaPhieuDat")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("NgayNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieuNhan");

                    b.HasIndex("MaPhieuDat")
                        .IsUnique()
                        .HasFilter("[MaPhieuDat] IS NOT NULL");

                    b.ToTable("PhieuNhanPhongs");
                });

            modelBuilder.Entity("KLCN060.Domain.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Tang")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoai");

                    b.ToTable("Phongs");
                });

            modelBuilder.Entity("KLCN060.Domain.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("NhomChucNang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen");

                    b.HasIndex("TenQuyen")
                        .IsUnique();

                    b.ToTable("Quyens");
                });

            modelBuilder.Entity("KLCN060.Domain.TaiKhoan", b =>
                {
                    b.Property<string>("TenDN")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LoaiTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhach")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanDangNhapSai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HOAT_DONG");

                    b.HasKey("TenDN");

                    b.HasIndex("MaKhach")
                        .IsUnique()
                        .HasFilter("[MaKhach] IS NOT NULL");

                    b.HasIndex("MaNV")
                        .IsUnique()
                        .HasFilter("[MaNV] IS NOT NULL");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("KLCN060.Domain.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTros");
                });

            modelBuilder.Entity("KLCN060.Domain.VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietHoaDon", b =>
                {
                    b.HasOne("KLCN060.Domain.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietKhuyenMai", b =>
                {
                    b.HasOne("KLCN060.Domain.KhuyenMai", "KhuyenMai")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaKM")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietKhuyenMais")
                        .HasForeignKey("MaPhieuDat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietPhieuDat", b =>
                {
                    b.HasOne("KLCN060.Domain.PhieuDatPhong", "PhieuDatPhong")
                        .WithMany("ChiTietPhieuDats")
                        .HasForeignKey("MaPhieuDat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.Phong", "Phong")
                        .WithMany("ChiTietPhieuDats")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuDatPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietPhieuNhan", b =>
                {
                    b.HasOne("KLCN060.Domain.PhieuNhanPhong", "PhieuNhanPhong")
                        .WithMany("ChiTietPhieuNhans")
                        .HasForeignKey("MaPhieuNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.Phong", "Phong")
                        .WithMany("ChiTietPhieuNhans")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhieuNhanPhong");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietSuDungDV", b =>
                {
                    b.HasOne("KLCN060.Domain.DichVu", "DichVu")
                        .WithMany("ChiTietSuDungDVs")
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.PhieuNhanPhong", "PhieuNhanPhong")
                        .WithMany("ChiTietSuDungDVs")
                        .HasForeignKey("MaPhieuNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("PhieuNhanPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.ChiTietThanhToan", b =>
                {
                    b.HasOne("KLCN060.Domain.HoaDon", "HoaDon")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.NhanVien", "NhanVienThuNgan")
                        .WithMany("ChiTietThanhToans")
                        .HasForeignKey("MaTaiKhoanThuNgan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("NhanVienThuNgan");
                });

            modelBuilder.Entity("KLCN060.Domain.CoSoVatChat", b =>
                {
                    b.HasOne("KLCN060.Domain.Phong", "Phong")
                        .WithMany("CoSoVatChats")
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("KLCN060.Domain.HoaDon", b =>
                {
                    b.HasOne("KLCN060.Domain.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.PhieuNhanPhong", "PhieuNhanPhong")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaPhieuNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("PhieuNhanPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.LichSuSaoLuu", b =>
                {
                    b.HasOne("KLCN060.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSuSaoLuus")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLCN060.Domain.NhanVien", b =>
                {
                    b.HasOne("KLCN060.Domain.VaiTro", "VaiTro")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("KLCN060.Domain.NhatKyBanGiaoCa", b =>
                {
                    b.HasOne("KLCN060.Domain.TaiKhoan", "TaiKhoanGiao")
                        .WithMany("NhatKyBanGiaoCaGiaos")
                        .HasForeignKey("MaTaiKhoanGiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.TaiKhoan", "TaiKhoanNhan")
                        .WithMany("NhatKyBanGiaoCaNhans")
                        .HasForeignKey("MaTaiKhoanNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoanGiao");

                    b.Navigation("TaiKhoanNhan");
                });

            modelBuilder.Entity("KLCN060.Domain.NhatKyThaoTac", b =>
                {
                    b.HasOne("KLCN060.Domain.TaiKhoan", "TaiKhoan")
                        .WithMany("NhatKyThaoTacs")
                        .HasForeignKey("MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuDatPhong", b =>
                {
                    b.HasOne("KLCN060.Domain.Khach", "Khach")
                        .WithMany("PhieuDatPhongs")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khach");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuDoiPhong", b =>
                {
                    b.HasOne("KLCN060.Domain.Phong", "PhongMoi")
                        .WithMany("PhieuDoiPhongMois")
                        .HasForeignKey("MaPhongMoi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.ChiTietPhieuNhan", "ChiTietPhieuNhanCu")
                        .WithMany()
                        .HasForeignKey("MaPhieuNhan", "MaPhongCu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietPhieuNhanCu");

                    b.Navigation("PhongMoi");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuNhanPhong", b =>
                {
                    b.HasOne("KLCN060.Domain.PhieuDatPhong", "PhieuDatPhong")
                        .WithOne("PhieuNhanPhong")
                        .HasForeignKey("KLCN060.Domain.PhieuNhanPhong", "MaPhieuDat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PhieuDatPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.Phong", b =>
                {
                    b.HasOne("KLCN060.Domain.LoaiPhong", "LoaiPhong")
                        .WithMany("Phongs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.TaiKhoan", b =>
                {
                    b.HasOne("KLCN060.Domain.Khach", "Khach")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("KLCN060.Domain.TaiKhoan", "MaKhach")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KLCN060.Domain.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("KLCN060.Domain.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Khach");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("KLCN060.Domain.VaiTroQuyen", b =>
                {
                    b.HasOne("KLCN060.Domain.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaQuyen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KLCN060.Domain.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("KLCN060.Domain.DichVu", b =>
                {
                    b.Navigation("ChiTietSuDungDVs");
                });

            modelBuilder.Entity("KLCN060.Domain.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");

                    b.Navigation("ChiTietThanhToans");
                });

            modelBuilder.Entity("KLCN060.Domain.Khach", b =>
                {
                    b.Navigation("PhieuDatPhongs");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLCN060.Domain.KhuyenMai", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");
                });

            modelBuilder.Entity("KLCN060.Domain.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("KLCN060.Domain.NhanVien", b =>
                {
                    b.Navigation("ChiTietThanhToans");

                    b.Navigation("HoaDons");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuDatPhong", b =>
                {
                    b.Navigation("ChiTietKhuyenMais");

                    b.Navigation("ChiTietPhieuDats");

                    b.Navigation("PhieuNhanPhong");
                });

            modelBuilder.Entity("KLCN060.Domain.PhieuNhanPhong", b =>
                {
                    b.Navigation("ChiTietPhieuNhans");

                    b.Navigation("ChiTietSuDungDVs");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("KLCN060.Domain.Phong", b =>
                {
                    b.Navigation("ChiTietPhieuDats");

                    b.Navigation("ChiTietPhieuNhans");

                    b.Navigation("CoSoVatChats");

                    b.Navigation("PhieuDoiPhongMois");
                });

            modelBuilder.Entity("KLCN060.Domain.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("KLCN060.Domain.TaiKhoan", b =>
                {
                    b.Navigation("LichSuSaoLuus");

                    b.Navigation("NhatKyBanGiaoCaGiaos");

                    b.Navigation("NhatKyBanGiaoCaNhans");

                    b.Navigation("NhatKyThaoTacs");
                });

            modelBuilder.Entity("KLCN060.Domain.VaiTro", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
